package solutions.trp.pmt.controller.api.response;

public enum ApiErrorCode {
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    DATABASE_ERROR,
    CONFLICT,
    INTERNAL_ERROR,
    BAD_REQUEST,
    INTEGRATION_AUTHENTICATION,
    INTEGRATION_TIMEOUT,
    INTEGRATION_INVALID_ACCOUNT,
    INTEGRATION_NOT_FOUND,
    INTEGRATION_UNAVAILABLE,
}
