logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security=DEBUG:

  file:
    path: logs

spring:
  web:
    resources:
      cache:
        cachecontrol:
          no-store: false
          cache-public: true
          max-age: 365d
  datasource:
    password: TRPnimda10
    url: jdbc:mysql://localhost:3306/pmt
    username: pmt

  jpa:
    hibernate:
      ddl-auto: create-only

    show-sql: false

    properties:
      hibernate:
        format_sql: true