logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security: DEBUG

  file:
    path: logs

spring:
  mail:
    host: smtp.trp.solutions
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          ssl:
            trust: smtp.trp.solutions

  web:
    resources:
      cache:
        cachecontrol:
          no-store: false
          cache-public: true
          max-age: 365d
  datasource:
    password:
    url:
    username:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

pmt:
  mail:
    enabled: true
  display:
    token:

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /pmt

feature-system:
  api-server:
  auth-id:
  auth-key:

api:
  key:
